name: dlbsweep
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_inappwebview: ^6.1.5
  http: ^1.3.0
  url_launcher: ^6.3.1
  url_launcher_android: ^6.3.14
  shared_preferences: ^2.3.5
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.1
  flutter_local_notifications: ^18.0.1
#  permission_handler: ^11.0.1
  flutter_foreground_task: ^8.17.0
  permission_handler: ^11.3.1
  flutter_background_service: ^5.1.0
  webview_flutter: ^4.10.0
  provider: ^6.1.2
  carousel_slider: ^5.0.0
#  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/button_list.json
    - assets/keells.jpeg
    - assets/foodCity.jpeg
    - assets/Damro.jpeg
    - assets/abans.jpeg
    - assets/dlbSweep.jpeg
    - assets/iit.jpeg
    - assets/welcome.jpg